version: '3.4'

services:
  tcbbbackendv1:
    image: tcbbbackendv1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
